name: shiksha_setu
description: A student dropout prediction and counseling app.
publish_to: 'none' 

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  translator: ^1.0.4+1
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  fl_chart: ^0.66.0
  provider: ^6.1.5+1
  http: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo.png
